application: twcl-hackthon
version: 1
api_version: 1
runtime: python27
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: hackthon.app

libraries:
- name: jinja2
  version: latest